require ("user.launch")
require ("user.options")
require ("user.keymaps")
spec ("user.colorscheme")
spec ("user.devicons")
spec ("user.treesitter")
spec ("user.mason")
spec ("user.schemastore")
spec ("user.lspconfig")
-- spec ("user.nvimtree")
require ("user.lazy")
